version: "3.8"
services:
  database-mysql:
    image: mysql
    container_name: mysql-forum
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  web-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database-mysql